# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SKInfo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SKInfo

end

target 'SKInfo WatchKit App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SKInfo WatchKit App

end

target 'SKInfo WatchKit Extension' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SKInfo WatchKit Extension

pod 'Charts'
end
